from pathlib import Path

# zapbench public release data
ZAPBENCH_GCS_URI = "gs://zapbench-release/volumes/20240930"
# read only, local copy of zarrs downloaded from URI above
ZAPBENCH_LOCAL_PATH = Path("/path/to/zapbench-release/volumes/20240930")

# these paths below need to be writeable, generated by us
ZAP_CELL_EPHYS_INDEX_PATH = Path("/path/to/cell_ephys_index.zarr")
NEUPRINT_DOWNLOAD_DIR = Path("/path/to/neuprint_data")
TRAINING_DIR = Path("/path/to/training_runs")
